"""Generate m7_mjx.xml — an MJX-compatible, arms-only kinematic model of M7.

Rationale (verified in code, 2026-07-23):
  sim/vec_env_jax.py::_apply_joints_single sets qpos then calls mjx.kinematics()
  — PURE forward kinematics, no physics stepping.  So the MJX model only needs a
  correct kinematic tree (body local pos/quat + hinge axis/range) from the torso
  down to each hand_frame.  Fingers, meshes, materials, textures, waist DoF are
  irrelevant and are dropped (mirrors robots/robonaut2/r2_mjx.xml).

Method: load m7.xml in MuJoCo, read the EXACT local transforms of the arm-chain
bodies/joints straight from the compiled model (no hand-transcription), and emit
a minimal MJX xml with the torso welded to the world at its zero-config world pose.

重跑它会和仓库里已提交的 m7_mjx.xml 差一行，这是已知的、无害的（2026-08-09 查清）::

    已提交:  right_hand_frame quat="0.717362 -0.690984 -0.072027 0.052397"
    重生成:  right_hand_frame quat="0.71736183 -0.69098384 -0.072026983 0.052396988"

原因：m7.xml 里那串 quat 是 ``fix_m7_handframe.py`` 打印的 6 位小数（见那个脚本的
``{q[0]:.6f}``），手工贴回 MJCF 的，模长 1.00000023 ≠ 1。本脚本读的是**编译后**的
``m.body_quat``，MuJoCo 编译时会归一化，于是按 ``%.8g`` 打出来就是全精度。
两者是同一个旋转：逐元素差 4.4e-9，旋转角差 2.4e-6 度；编译成模型后 body_quat
差 1.9e-9（不是逐位相同，只是归一化的浮点结合顺序不同）。

**保留已提交的那份**，不用重生成的覆盖。理由不是"差得小"，而是：根模型的
checkpoint 是拿已提交这份的 FK 训出来的，为 2e-6 度去动一个训练依赖的资产是纯粹的
无谓风险。真要重生成，必须重跑 ``verify_m7_mjx_fk.py`` + ``check_handframe_convention.py``
并说明为什么值得动。
"""
from pathlib import Path

from web2robot.paths import P
import numpy as np
import mujoco

SRC = P.asset("m7_mjcf")                 # assets/robots/m7/m7.xml
DST = SRC.parent / "m7_mjx.xml"          # 产物；P.asset("m7_mjx") 要求已存在，这里是要生成它

TORSO = "waist_pitch_link"
ARM_BODIES = {
    "left":  ["left_shoulder_pitch_link", "left_shoulder_roll_link", "left_arm_yaw_link",
              "left_elbow_pitch_link", "left_elbow_yaw_link", "left_wrist_pitch_link",
              "left_wrist_roll_link", "left_hand_frame"],
    "right": ["right_shoulder_pitch_link", "right_shoulder_roll_link", "right_arm_yaw_link",
              "right_elbow_pitch_link", "right_elbow_yaw_link", "right_wrist_pitch_link",
              "right_wrist_roll_link", "right_hand_frame"],
}
# joint per body (hand_frame has none); name = "<body without _link>_joint"
def joint_of(body):
    if body.endswith("_hand_frame"):
        return None
    return body.replace("_link", "_joint")

m = mujoco.MjModel.from_xml_path(str(SRC))
d = mujoco.MjData(m)
mujoco.mj_resetData(m, d)
mujoco.mj_forward(m, d)  # zero config

def bid(name): return mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, name)
def jid(name): return mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_JOINT, name)

# torso world pose at zero config (waist welded here)
tid = bid(TORSO)
torso_pos = d.xpos[tid].copy()
torso_quat = d.xquat[tid].copy()  # wxyz

def fmt(a): return " ".join(f"{x:.8g}" for x in np.asarray(a).ravel())

lines = []
lines.append('<mujoco model="m7_mjx">')
lines.append('  <!-- AUTO-GENERATED by scripts/dev/generate_m7_mjx.py from m7.xml.')
lines.append('       Arms-only kinematic tree for MJX training (mjx.kinematics FK).')
lines.append('       Fingers/meshes/materials/waist DoF dropped; torso welded to world. -->')
lines.append('  <compiler angle="radian"/>')
lines.append('  <option integrator="implicitfast" timestep="0.004" iterations="4" ls_iterations="8"/>')
lines.append('  <default>')
lines.append('    <joint damping="10" frictionloss="0"/>')
lines.append('    <position inheritrange="1"/>')
lines.append('    <geom contype="0" conaffinity="0"/>')
lines.append('  </default>')
lines.append('  <worldbody>')
lines.append(f'    <body name="{TORSO}" pos="{fmt(torso_pos)}" quat="{fmt(torso_quat)}">')
lines.append('      <inertial pos="0 0 0" mass="10" diaginertia="0.5 0.5 0.5"/>')
lines.append('      <geom type="box" size="0.12 0.12 0.15" rgba="0.5 0.5 0.5 1"/>')

INDENT = "      "
act_joints = []
for side in ("left", "right"):
    depth = 0
    for body in ARM_BODIES[side]:
        b = bid(body)
        bpos = m.body_pos[b].copy()
        bquat = m.body_quat[b].copy()  # wxyz
        pad = INDENT + "  " * (depth + 1)
        jn = joint_of(body)
        if jn is None:
            # hand_frame: leaf fixed body, no joint, no inertia needed
            lines.append(f'{pad}<body name="{body}" pos="{fmt(bpos)}" quat="{fmt(bquat)}"/>')
            # close all opened arm bodies for this side
            for _ in range(depth):
                pad2 = INDENT + "  " * depth
                lines.append(f'{pad2}</body>')
                depth -= 1
            break
        j = jid(jn)
        axis = m.jnt_axis[j].copy()
        lo, hi = m.jnt_range[j]
        lines.append(f'{pad}<body name="{body}" pos="{fmt(bpos)}" quat="{fmt(bquat)}">')
        pad_c = pad + "  "
        lines.append(f'{pad_c}<joint name="{jn}" type="hinge" axis="{fmt(axis)}" range="{lo:.6g} {hi:.6g}"/>')
        lines.append(f'{pad_c}<inertial pos="0 0 0" mass="0.8" diaginertia="0.01 0.01 0.01"/>')
        lines.append(f'{pad_c}<geom type="capsule" size="0.03" fromto="0 0 0 0 0 -0.15" rgba="0.6 0.6 0.8 1"/>')
        act_joints.append(jn)
        depth += 1

lines.append('    </body>')   # close torso
lines.append('  </worldbody>')
lines.append('  <actuator>')
for jn in act_joints:
    lines.append(f'    <position name="{jn}_servo" joint="{jn}" kp="50"/>')
lines.append('  </actuator>')
lines.append('</mujoco>')

DST.write_text("\n".join(lines) + "\n")
print(f"wrote {DST}  ({len(act_joints)} actuated joints)")

# quick self-check: reload generated file
m2 = mujoco.MjModel.from_xml_path(str(DST))
print(f"reload OK: nq={m2.nq} nbody={m2.nbody} njnt={m2.njnt}")
